// seed-job/Jenkinsfile
def pipelines = []

// Generate 50 pipeline names
for (int i = 1; i <= 50; i++) {
    pipelines.add("pipeline-${i}")
}

job('generate-multiple-pipelines') {
    description('Generates 50 pipeline jobs from a single template')
    
    steps {
        dsl {
            pipelines.each { pipelineName ->
                text("""
                    pipelineJob('${pipelineName}') {
                        definition {
                            cpsScm {
                                scm {
                                    git {
                                        remote {
                                            url('https://github.com/Rai-13/jenkins-pipelines.git')
                                            branch('main')
                                        }
                                    }
                                }
                                scriptPath('generic-pipeline/Jenkinsfile')
                            }
                        }
                        
                        parameters {
                            stringParam('PIPELINE_NAME', '${pipelineName}', 'Name of the pipeline')
                            choiceParam('BEHAVIOR', ['success', 'fail', 'random', 'slow'], 'Pipeline behavior')
                        }
                        
                        triggers {
                            cron('*/5 * * * *')
                        }
                    }
                """)
            }
        }
    }
}
